config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards, only: %i[index new create edit update destory] do
    resources :tasks do
      resources :comments, only: %i[new create]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# frozen_string_literal: true

class Board < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  def has_been_written?(task)
    tasks.exists?(id: task.id)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  has_one_attached :eyecatch

  has_many :comments, dependent: :destroy
  belongs_to :board
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy

  def has_written?(board)
    boards.exists?(id: board.id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
# frozen_string_literal: true

class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to boards_path
    else
      render :new
    end
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def update
    @board = current_user.boards.find(params[:id])
    if @board.update(board_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    board = current_user.boards.find(params[:id])
    board.destroy
    redirect_to root_path
  end

  private

  def board_params
    params.require(:board).permit(:title, :content)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:task_id])
    @comment = @task.comments.build
  end

  def create
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:task_id])
    @comment = @task.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to board_task_path(@board, @task)
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    @board = Board.find(params[:board_id])
  end

  def show
    @board = Board.find(params[:board_id])
    @task = Task.find(params[:id])
    @comments = @task.comments
  end

  def new
    @board = Board.find(params[:board_id])
    @task = @board.tasks.build
  end

  def create
    board = Board.find(params[:board_id])
    @task = board.tasks.build(task_params)
    if @task.save
      redirect_to board_tasks_path(board)
    else
      render :new
    end
  end

  def edit
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:id])
  end

  def update
    board = Board.find(params[:board_id])
    @task = board.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to board_tasks_path(board)
    else
      render :edit
    end
  end

  def destroy
    board = Board.find(params[:board_id])
    task = board.tasks.find(params[:id])
    task.destroy
    redirect_to board_tasks_path(board)
  end

  private

  def task_params
    params.require(:task).permit(:title, :content, :eyecatch)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/boards/edit.html.haml
.container
  %h2 Edit board
  = form_with(model: @board, url: board_path(@board), method: 'put' , local: true) do |f|
    %div
      = f.label :title ,'Name'
    %div
      = f.text_field :title , class: 'text'
    %div
      = f.label :content ,'Description'
    %div
      = f.text_area :content, class: 'long-text'
    = f.submit 'Submit' , class: 'submit'

app/views/boards/index.html.haml
.container 
  %h2 All Boards
  - @boards.each do |board|
    .card
      .card_content
        .card_upper
          = link_to board_tasks_path(board) do
            .card_title
              = board.title
          .dropdown 
            - if user_signed_in? && current_user.has_written?(board)
              = image_tag 'Combined Shape.png', class: 'dropdown'
              .dropdown-content
                =link_to 'Edit', edit_board_path(board)
                =link_to 'Delete', board_path(board), data: {method: 'delete', confirm: 'Are you sure to delete this board?'}
        = link_to board_tasks_path(board) do    
          .card_detail
            = board.content
          .card_auther_image
          = image_tag 'Oval.png', class: 'avatar-image'

  = link_to new_board_path do
    .board-float_btn
      %p +Add new board

app/views/boards/new.html.haml
.container
  %h2 New board
  = render 'form', board: @board

app/views/comments/new.html.haml
.container
  %h2 New Comment
  = form_with(model: @comment ,url: board_task_comments_path(@board, @task), method: 'post', local: true) do |f|
    %div
      = f.text_area :content, class: 'long-text'
    = f.submit 'Submit' , class: 'submit'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TodoApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{:href => "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  %body
    %p.notice= notice
    %p.alert= alert
    %header.header 
      .header_logos
        %p.header_pageTitle
          = link_to 'Boards', root_path
        -if user_signed_in?
          = image_tag 'Oval.png', class: 'header_avatar'
        %p.header_border
    = yield

app/views/tasks/edit.html.haml
.container
  %h2 Edit task
  = form_with(model: @task ,url: board_task_path(@board,@task), method: 'put', local: true) do |f|
    %div 
      = f.label :eyecatch, 'Eyecatch'
    %div 
      = f.file_field :eyecatch, class: 'eyecatch'
    %div
      = f.label :title ,'Name'
    %div
      = f.text_field :title , class: 'text'
    %div
      = f.label :content ,'Description'
    %div
      = f.text_area :content, class: 'long-text'
    = f.submit 'Submit' , class: 'submit'

app/views/tasks/index.html.haml
.container
  %h2= @board.title
  - @tasks.each do |task|
    = link_to board_task_path(@board,task.id) do
      .task-card
        - if task.eyecatch.attached?
          .card_image
            = image_tag task.eyecatch
        .task-card_title
          = task.title  
        .task-card_content
          = task.content
        .task-card_buttom
          .task-card_avatar
            = image_tag 'Oval.png', class: 'task-avatar'
          .comment-count
= link_to new_board_task_path do
  .task-float_btn
    %p +Add new card
  

app/views/tasks/new.html.haml
.container
  %h2 New card
  = form_with(model: @task ,url: board_tasks_path, method: 'post', local: true) do |f|
    %div 
      = f.label :eyecatch, 'Eyecatch'
    %div 
      = f.file_field :eyecatch, class: 'eyecatch'
    %div
      = f.label :title ,'Name'
    %div
      = f.text_field :title , class: 'text'
    %div
      = f.label :content ,'Description'
    %div
      = f.text_area :content, class: 'long-text'
    = f.submit 'Submit' , class: 'submit'

app/views/tasks/show.html.haml
.container
  .task_topper
    %h2= @task.title
    .dropdown
      - if user_signed_in? && @board.has_been_written?(@task)
        = image_tag 'Combined Shape.png', class: 'dropdown'
        .dropdown-content
          =link_to 'Edit', edit_board_task_path(@board,@task)
          =link_to 'Delete', board_task_path(@board,@task), data: {method: 'delete', confirm: 'Are you sure to delete this board?'}
  - if @task.eyecatch.attached?
    .card_image_show
      = image_tag @task.eyecatch
  .task_content
    = @task.content
  .task_comment
    %p Comment
    -@comments.each do |comment|
      .comment_detail
        .comment_image
          = image_tag 'Oval.png'
        .comment_content
          = comment.content
    = link_to new_board_task_comment_path(@board, @task) do
      .comment_float_btn
        %p +Add new comment